from __future__ import annotations

import csv
import os
from dataclasses import dataclass
from pathlib import Path

from dotenv import load_dotenv


def resolve_project_path(project_root: Path, value: str | Path) -> Path:
    path = Path(value).expanduser()
    return (path if path.is_absolute() else project_root / path).resolve()


def _read_qwen_credentials(path: Path) -> dict[str, str]:
    """Read the two-column credential CSV exported by Model Studio.

    The second column name is generated by the console, so values are read by
    position instead of assuming a fixed header. The API key is never logged.
    """
    if not path.is_file():
        raise FileNotFoundError(f"Qwen credentials file not found: {path}")

    credentials: dict[str, str] = {}
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.reader(handle)
        next(reader, None)
        for row in reader:
            if len(row) >= 2 and row[0].strip():
                credentials[row[0].strip()] = row[1].strip()
    return credentials


@dataclass(frozen=True)
class Settings:
    project_root: Path
    data_dir: Path
    llm_mode: str
    qwen_api_key: str
    qwen_base_url: str
    qwen_model: str
    llm_debug: bool
    llm_log_dir: Path
    tts_mode: str
    qwen_tts_base_url: str
    qwen_tts_model: str
    qwen_tts_voice: str
    qwen_tts_optimize_instructions: bool
    tts_output_dir: Path
    float_worker_url: str
    float_worker_timeout_seconds: float
    float_transfer_mode: str
    float_reference_image: Path
    float_no_crop: bool
    avatar_segment_max_chars: int
    avatar_reference_image: Path
    avatar_idle_video: Path
    course_media_cache_dir: Path
    rag_embedding_model: Path
    rag_embedding_device: str
    rag_embedding_batch_size: int
    asr_model_dir: Path | None = None
    asr_num_threads: int = 2

    @property
    def checkpoint_db(self) -> Path:
        return self.data_dir / "checkpoints.sqlite3"

    @property
    def profile_db(self) -> Path:
        return self.data_dir / "profiles.sqlite3"

    @property
    def conversation_db(self) -> Path:
        return self.data_dir / "conversations.sqlite3"

    def ensure_directories(self) -> None:
        self.data_dir.mkdir(parents=True, exist_ok=True)

    @classmethod
    def from_env(cls) -> "Settings":
        project_root = Path(__file__).resolve().parents[1]
        load_dotenv(project_root / ".env", override=False)

        def configured_path(name: str, default: str) -> Path:
            return resolve_project_path(project_root, os.getenv(name, "").strip() or default)

        credentials: dict[str, str] = {}
        credentials_file = os.getenv("VT_QWEN_CREDENTIALS_FILE", "").strip()
        if credentials_file:
            credentials = _read_qwen_credentials(
                resolve_project_path(project_root, credentials_file)
            )

        api_key = os.getenv(
            "VT_QWEN_API_KEY", os.getenv("DASHSCOPE_API_KEY", "")
        ).strip()
        if not api_key:
            api_key = credentials.get("apiKey", "")

        base_url = os.getenv("VT_QWEN_BASE_URL", "").strip()
        if not base_url:
            base_url = credentials.get(
                "openAiCompatible",
                "https://dashscope.aliyuncs.com/compatible-mode/v1",
            )

        tts_base_url = os.getenv("VT_QWEN_TTS_BASE_URL", "").strip()
        if not tts_base_url:
            tts_base_url = credentials.get(
                "dashScope",
                "https://dashscope.aliyuncs.com/api/v1",
            )

        settings = cls(
            project_root=project_root,
            data_dir=configured_path("VT_DATA_DIR", "data"),
            llm_mode=os.getenv("VT_LLM_MODE", "rule").strip().lower(),
            qwen_api_key=api_key,
            qwen_base_url=base_url,
            qwen_model=os.getenv("VT_QWEN_MODEL", "qwen3.7-flash").strip(),
            llm_debug=os.getenv("VT_LLM_DEBUG", "false").strip().lower()
            in {"1", "true", "yes", "on"},
            llm_log_dir=configured_path("VT_LLM_LOG_DIR", "logs"),
            tts_mode=os.getenv("VT_TTS_MODE", "qwen").strip().lower(),
            qwen_tts_base_url=tts_base_url.rstrip("/"),
            qwen_tts_model=os.getenv(
                "VT_QWEN_TTS_MODEL", "qwen3-tts-instruct-flash"
            ).strip(),
            qwen_tts_voice=os.getenv("VT_QWEN_TTS_VOICE", "Cherry").strip(),
            qwen_tts_optimize_instructions=os.getenv(
                "VT_QWEN_TTS_OPTIMIZE_INSTRUCTIONS", "false"
            ).strip().lower()
            in {"1", "true", "yes", "on"},
            tts_output_dir=configured_path("VT_TTS_OUTPUT_DIR", "outputs/audio"),
            float_worker_url=os.getenv(
                "VT_FLOAT_WORKER_URL", "http://127.0.0.1:8011"
            ).strip().rstrip("/"),
            float_worker_timeout_seconds=float(
                os.getenv("VT_FLOAT_WORKER_TIMEOUT_SECONDS", "10")
            ),
            float_transfer_mode=os.getenv(
                "VT_FLOAT_TRANSFER_MODE", "path"
            ).strip().lower(),
            float_reference_image=configured_path("VT_FLOAT_REFERENCE_IMAGE", "assets/teacher/real-teacher-002.png"),
            float_no_crop=os.getenv("VT_FLOAT_NO_CROP", "false").strip().lower()
            in {"1", "true", "yes", "on"},
            avatar_segment_max_chars=max(
                20,
                min(600, int(os.getenv("VT_AVATAR_SEGMENT_MAX_CHARS", "110"))),
            ),
            avatar_reference_image=configured_path("VT_AVATAR_REFERENCE_IMAGE", "assets/teacher/real-teacher-002-float-aligned.png"),
            avatar_idle_video=configured_path("VT_AVATAR_IDLE_VIDEO", "assets/private/idle.mp4"),
            course_media_cache_dir=configured_path("VT_COURSE_MEDIA_CACHE_DIR", "outputs/course-media"),
            rag_embedding_model=configured_path("VT_RAG_EMBEDDING_MODEL", "../models/bge-small-zh-v1.5"),
            rag_embedding_device=os.getenv(
                "VT_RAG_EMBEDDING_DEVICE", "cpu"
            ).strip().lower(),
            rag_embedding_batch_size=max(
                1, min(64, int(os.getenv("VT_RAG_EMBEDDING_BATCH_SIZE", "8")))
            ),
            asr_model_dir=configured_path("VT_ASR_MODEL_DIR", "../models/sensevoice-small-int8"),
            asr_num_threads=max(1, min(4, int(os.getenv("VT_ASR_NUM_THREADS", "2")))),
        )
        settings.ensure_directories()
        return settings
